server:
  port: 7001
  servlet:
    context-path: /system-center
# 数据源配置
spring:
  messages:
    basename: i18n/messages
  profiles:
    include: db-dev,redis-dev

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

gen:
  author: cc
  packageName: cn.oneplustow.xx