ruoyi:
  juheApiIpKey: ENC(44JKicZzX2ORMFQmdbbkldndARlVRJ89rc/zZ2As5RON9GTyQ0BSXvrY3UJ2Y5kdn9SwI4tRNAA=)
server:
  port: 7003
  servlet:
    context-path: /auth-center
# 数据源配置
spring:
  messages:
    basename: i18n/messages
  profiles:
    include: db-prod,redis-prod
  main:
    allow-bean-definition-overriding: true
# token配置
token:
  # 令牌自定义标识
  header: authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 5000
