
server:
  port: 7004
  servlet:
    context-path: /live-center
# 数据源配置
spring:
  messages:
    basename: i18n/messages
  profiles:
    include: db-prod
  main:
    allow-bean-definition-overriding: true
feign:
  sentinel:
    enabled: true
ribbon:
  ReadTimeout: 5000
protocol: https
